### PR TITLE
get_config match 'end' keywork instead '#'

### PR DESCRIPTION
**Pull request by eczema**
Sometimes # is present in the config body... 
end keyword is a better match

### CODE REVIEW

**Comment by fallenfuzz** [comment]
Tested and works ok?

**Comment by fallenfuzz** [comment]
export doesn't work
send your skype ID please

**Comment by eczema** [comment]
Tested with xrv...  and a very very long config.
The original code exit before end because '#' are used in comments and banner

What doesn't work ? 

For chat , I prefer IRC ...

**Comment by fallenfuzz** [comment]
Lets meet here http://webchat.freenode.net/?channels=%23UNetLab

**Comment by eczema** [comment]
ok I'm in

**Pull request closed without merging**
